services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram_bot_api
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: 1
    ports:
      - "18081:8081"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

  tt-bot:
    build: .
    container_name: tt_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_API_BASE_URL: http://telegram-bot-api:8081
      TELEGRAM_BOT_API_IS_LOCAL: "1"
    depends_on:
      - telegram-bot-api
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt
      - ./cache.db:/app/cache.db

volumes:
  telegram-bot-api-data:
